const walletsListMap = {
	'Apex Wallet': 'apexWallet',
	Avalanche: 'avalanche',
	Backpack: 'backpack',
	Bifrost: 'bifrost',
	BitKeep: 'bitKeep',
	Bitski: 'bitski',
	'Block Wallet': 'blockWallet',
	'Brave Wallet': 'braveWallet',
	'Coinbase Wallet': 'coinbaseWallet',
	Dawn: 'dawn',
	Enkrypt: 'enkrypt',
	Exodus: 'exodus',
	Frame: 'frame',
	Frontier: 'frontier',
	'GameStop Wallet': 'gamestop',
	HyperPay: 'hyperPay',
	imToken: 'imToken',
	'KuCoin Wallet': 'kuCoinWallet',
	MathWallet: 'mathWallet',
	MetaMask: 'metaMask',
	'OKX Wallet': 'okxWallet',
	'OKEx Wallet': 'okExWallet',
	'1inch Wallet (Android)': 'oneInchAndroidWallet',
	'1inch Wallet (iOS)': 'oneInchIOSWallet',
	Opera: 'opera',
	Phantom: 'phantom',
	Portal: 'portal',
	Rabby: 'rabby',
	Rainbow: 'rainbow',
	Status: 'status',
	Tally: 'tally',
	TokenPocket: 'tokenPocket',
	Tokenary: 'tokenary',
	Trust: 'trust',
	'Trust Wallet': 'trustWallet',
	'Uniswap Wallet': 'uniswapWallet',
	XDEFI: 'xDEFI',
	Zerion: 'zerion',
};

export default walletsListMap;
